create or replace TABLE BIBIBIG.BRONZE_STATE_DATA.AIRCRAFT_DEPARTURE_ARRIVAL (
	ICAO24 VARCHAR(50) NOT NULL,
	FIRSTSEEN NUMBER(38,0),
	ESTDEPARTUREAIRPORT VARCHAR(15),
	LASTSEEN NUMBER(38,0),
	ESTARRIVALAIRPORT VARCHAR(15),
	CALLSIGN VARCHAR(50),
	ESTDEPARTUREAIRPORTHORIZDISTANCE NUMBER(38,0),
	ESTDEPARTUREAIRPORTVERTDISTANCE NUMBER(38,0),
	ESTARRIVALAIRPORTHORIZDISTANCE NUMBER(38,0),
	ESTARRIVALAIRPORTVERTDISTANCE NUMBER(38,0),
	DEPARTUREAIRPORTCANDIDATESCOUNT NUMBER(38,0),
	ARRIVALAIRPORTCANDIDATESCOUNT NUMBER(38,0),
	CREATEAT TIMESTAMP_NTZ(9) NOT NULL
);